<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span><ul class="toc-item"><li><span><a href="#Линейная-регрессия-до-преобразования-персональных-данных" data-toc-modified-id="Линейная-регрессия-до-преобразования-персональных-данных-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Линейная регрессия до преобразования персональных данных</a></span></li><li><span><a href="#Создание-матрицы-и-получение-преобразованных-признаков" data-toc-modified-id="Создание-матрицы-и-получение-преобразованных-признаков-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Создание матрицы и получение преобразованных признаков</a></span></li><li><span><a href="#Линейная-регрессия-после-преобразования-персональных-данных" data-toc-modified-id="Линейная-регрессия-после-преобразования-персональных-данных-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Линейная регрессия после преобразования персональных данных</a></span></li><li><span><a href="#Вывод" data-toc-modified-id="Вывод-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Вывод</a></span></li></ul></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

Загрузим и изучим исходные данные:

In [ ]:
data = pd.read_csv('/datasets/insurance.csv')
data.head()

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


Пропусков ни в одном из столбцов нет, типы данных подходят для задачи линейной регрессии.

Проверим данные на наличие дубликатов:

In [ ]:
data.duplicated().sum()

153

In [ ]:
data = data.drop_duplicates().reset_index(drop=True)

In [ ]:
data.duplicated().sum()

0

Данные готовы для дальнейшей работы

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.*

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** Качество линейной регрессии не изменится.

**Обоснование:** Качество линейной регрессии не изменится при умножении признаков на обратимую матрицу, так как в данном случае признаки не исчезают и не пропадают, а просто переходят в новые линейно независимые признаки (происходит преобразование исходных признаков в новые). А предсказания модели не изменятся, в следствие того, что пространство и ранги матрицы признаков также останутся неизменными, просто в новых координатах.

$$
a = Xw
$$

$$
a = X(X^T X)^{-1} X^T y = XX^{-1}(X^T)^{-1}X^Ty = y
$$

$$
a_1 = XPw_1
$$

$$
w_1 = ((XP)^T (XP))^{-1} (XP)^T y
$$

$$
a_1 = XP ((XP)^T (XP))^{-1} (XP)^T y
$$

$$
a_1 = XP P^{-1} ((XP)^T X)^{-1} P^T X^T y
$$

$$
a_1 = XP P^{-1} (P^T X^T X)^{-1} P^T X^T y
$$

$$
a_1 = XP P^{-1} (X^T X)^{-1} (P^T)^{-1} P^T X^T y
$$

$$
a_1 = XP P^{-1} (X^T X)^{-1} X^T y
$$

$$
a_1 = XP P^{-1} w = Xw
$$

$$
a_1 = a = Xw
$$

Параметры модели будут связаны с параметрами исходной модели линейным преобразованием, которое не изменяет качество модели.

## Алгоритм преобразования

**Алгоритм**

1. Создание случайно сгенерированной квадратной обратимой матрицы Р.
2. Проверка матрицы Р на обратимость.
3. Умножение матрицы признаков Х на полученную матрицу Р.
4. Обучение и сравнение качества модели до и после преобразования.

**Обоснование**

Качество модели линейной регрессии не изменится, поскольку умножение признаков на обратимую матрицу не меняет их линейной зависимости и не приводит к потере информации. Исходные признаки только поменяют свои координаты в пространстве, а их линейные коэффициенты не изменятся и не изменят качество модели.

## Проверка алгоритма

Определим признаки и целевую переменную и проверим их размерность:

In [ ]:
X = data.drop('Страховые выплаты', axis=1)   # матирца признаков (features)
y = data['Страховые выплаты']    # целевой признак

In [ ]:
display(X.shape)
y.shape

(4847, 4)

(4847,)

### Линейная регрессия до преобразования персональных данных

Разделим данные на обучающую и тестовую выборки:

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=12345)

In [ ]:
display(X_train.shape)
display(X_test.shape)
display(y_train.shape)
display(y_test.shape)

(3635, 4)

(1212, 4)

(3635,)

(1212,)

Обучим модель и получим ее качество на первоначальных данных:

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)
prediction = model.predict(X_test)
r2_before = r2_score(y_test, prediction)
print('Значения R^2 до преобразований:', r2_before)

Значения R^2 до преобразований: 0.42307727492147584


### Создание матрицы и получение преобразованных признаков

Получим случайную квадратную матрицу, размер которой соответствует количеству столбцов в исходной матрице признаков:

In [ ]:
P = np.random.normal(1, 30, (X.shape[1], X.shape[1]))
P

array([[-43.04432784,  -0.16376806, -65.09721424,  39.04752963],
       [-28.66118099, -53.98655194, -23.26209827, -19.25141672],
       [ 26.94754362,  14.65956164,  12.34174419,   7.17302319],
       [ 38.09358777,  29.95688835,  24.49223473, -29.59752552]])

Проверим полученную матрицу на обратимость:

In [ ]:
P1 = np.linalg.inv(P)
P1

array([[ 0.00695081,  0.02066058,  0.05677086,  0.00949016],
       [ 0.00633976, -0.01893596, -0.02923294,  0.01359598],
       [-0.02136196, -0.01818747, -0.02260543, -0.02183109],
       [-0.00231443, -0.00762492,  0.02477302, -0.02587665]])

In [ ]:
np.dot(P, P1)

array([[ 1.00000000e+00,  1.53261271e-16,  6.00850949e-16,
         4.05432646e-17],
       [-8.14982969e-17,  1.00000000e+00,  1.80070160e-16,
        -1.62020206e-16],
       [ 1.23081720e-17,  2.65690305e-17,  1.00000000e+00,
        -1.92724682e-17],
       [-6.92105627e-17, -1.30196116e-16, -2.25447563e-16,
         1.00000000e+00]])

Умножим исходные данные на полученную матрицу, чтобы получить новые зашифрованные персональные данные:

In [ ]:
X2 = X.values @ P
X2

array([[1335418.104405  ,  724930.60191893,  611156.1608208 ,
         355002.09207731],
       [1022726.33683273,  554609.9178836 ,  467940.71493845,
         271659.71847537],
       [ 565067.2417771 ,  306285.18446937,  258502.02714246,
         150075.1958775 ],
       ...,
       [ 913024.69228305,  495939.32239144,  417968.87054873,
         242721.26271093],
       [ 880625.36683668,  478269.66843782,  403071.64834455,
         234084.58205518],
       [1093262.80717538,  593696.37231888,  500382.87038733,
         290695.15179651]])

### Линейная регрессия после преобразования персональных данных

In [ ]:
X2_train, X2_test, y_train, y_test = train_test_split(
    X2, y, test_size=0.25, random_state=12345)

In [ ]:
display(X2_train.shape)
display(X2_test.shape)
display(y_train.shape)
display(y_test.shape)

(3635, 4)

(1212, 4)

(3635,)

(1212,)

In [ ]:
model = LinearRegression()
model.fit(X2_train, y_train)
prediction = model.predict(X2_test)
r2_after = r2_score(y_test, prediction)
print('Значения R^2 после преобразований:', r2_after)

Значения R^2 после преобразований: 0.4230772749215974


Сравним качество до и после преобразования:

In [ ]:
print('Значения R^2 до преобразований:', r2_before)
print('Значения R^2 после преобразований:', r2_after)

Значения R^2 до преобразований: 0.42307727492147584
Значения R^2 после преобразований: 0.4230772749215974


Качество модели не изменилось.

### Вывод

В ходе проекта был разработан метод шифрования, при котором сложно восстановить персональную информацию и который не влияет на качество регрессионной модели.